version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge # volume指定含めたdocker-composeが利用可能
    steps:
    - checkout
    # - run:
    #     name: init_container.sh # rails newやbundle installしている（詳しくはリポジトリ確認して下さい）
    #     command: sudo bash init_container.sh
    - run:
        name: up_service.sh #　db create migrate後にdocker-compose up
        command: bash up_service.sh
    # - run:
    #     name: exec rspec #　rspec実行 テスト結果をHTML出力
    #     command: docker-compose run app bundle exec rspec --format p --format html --out test-results/rspec.html
    # - store_artifacts: #　テスト結果をビルド情報画面で確認出来る様に格納先を指定
    #     path: myapp/test-results/rspec.html
    #     destination: rspec.html
    - run:
        name: docker-compose down
        command: docker-compose down
  deploy-prod: #本番環境への実行内容　Herokuアプリ名の環境変数値だけが違う
    machine:
      image: circleci/classic:edge
    steps:
    - checkout
    - run:
        name: heroku maintenance on
        command: heroku maintenance:on --app ${HEROKU_APP_NAME_PROD}
    - run:
        name: heroku deploy
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git master
    - run:
        name: create result table
        command: heroku run rails g model Result MachineGuid: string Cleared: string DateTime: string Disqualified: string Grade: string Guid: string Held: string LetGo: string MissedHold: string LifeRemainingSeconds: string MachineGuid: string MaxCombo: string Modifiers: string Pad: string PercentDP: string PlayerGuid: string ProductID: string Air: string Chaos: string Fakes: string Freeze: string Hands: string Holds: string Jumps: string Lifts: string Mines: string Notes: string Rolls: string Stream: string TapsAndHolds: string Voltage: string Score: string StageGuid: string SurviveSeconds: string AvoidMine: string CheckpointHit: string CheckpointMiss: string HitMine: string Miss: string W1: string W2: string W3: string W4: string W5: string Dir: string Difficulty: string Level: string StepsType: string _id: string _index: string _score: string _type: string
    - run:
        name: migrate
        command: heroku run rails db:migrate --app ${HEROKU_APP_NAME_PROD}
    - run:
        name: seed
        command: heroku run rails db:seed --app ${HEROKU_APP_NAME_PROD}
    - run:
        name: heroku maintenance off
        command: heroku maintenance:off --app ${HEROKU_APP_NAME_PROD}
workflows:
  version: 2
  build_and_deploy:
    jobs:
    # - build
    - deploy-prod:
        # requires:
        # - build
        filters:
          branches:
            only: master # masterブランチの変更に対してのみdeploy-prodジョブ実行