version: 2
jobs:
  deploy-prod: #本番環境への実行内容　Herokuアプリ名の環境変数値だけが違う
    machine:
      image: circleci/classic:edge
    steps:
    - checkout
    - run:
        name: heroku maintenance on
        command: heroku maintenance:on --app ${HEROKU_APP_NAME_PROD}
    - run:
        name: heroku deploy
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git master
    - run:
        name: delete psql
        command: heroku pg:reset DATABASE_URL --app ${HEROKU_APP_NAME_PROD} --confirm ${HEROKU_APP_NAME_PROD}
    - run:
        name: migrate
        command: heroku run rails db:migrate DISABLE_DATABASE_ENVIRONMENT_CHECK=1 --app ${HEROKU_APP_NAME_PROD}
    - run:
        name: seed
        command: heroku run rails db:seed --app ${HEROKU_APP_NAME_PROD}
    - run:
        name: heroku maintenance off
        command: heroku maintenance:off --app ${HEROKU_APP_NAME_PROD}
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - deploy-prod:
        filters:
          branches:
            only: master # masterブランチの変更に対してのみdeploy-prodジョブ実行